language: python
env:
  matrix:
    - JULIA_VERSION=1.5

matrix:
  include:
    - JULIA_VERSION=1.5
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
  
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  #- conda update -q conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas networkx numpydoc numba xlsxwriter xlrd
  - source activate test-environment
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
         conda uninstall numba --yes;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
         pip install pypower;
    fi
  - conda install matplotlib --yes
  - conda install -c conda-forge python-igraph --yes
  - pip install pytest pytest-cov
  - pip install codecov
  - python setup.py install
  - conda list
  - conda info -a

before_script:
  # this is needed to test PowerModels and julia code
  - echo .install_julia.sh "$JULIA_VERSION"
  - .install_julia.sh "$JULIA_VERSION"
  - which python
  - python -m pip install julia
  - python -m pip --version
  - python .install_pycall.py

script:
    py.test --cov=pandapower --cov-config .coveragerc
    
after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
          codecov;
      fi
